version: 2.1
jobs:
  test:
    docker:
      - image: cimg/openjdk:18.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=ovallejo_lulobank
      - run:
          name: Automation Test
          command: mvn clean verify
      - store_artifacts:
          path: target/site/serenity
workflows:
  main:
    jobs:
      - test:
          context: SonarCloud

